[tool.poetry]
name = "consumable"
version = "1.1.0"
description = ""
authors = ["taitep <arvid@h.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
